/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function(knex) {
  // Добавляем объекты недвижимости
  await knex('houses').insert([
    {
      name: 'Красивый дом на берегу озера',
      prev_text: 'Прекрасный вид на озеро',
      text: 'Этот великолепный дом расположен на берегу живописного озера. Бассейн и сауна в доме. Идеально подходит для семейного отдыха.',
      start_price: 50000000,
      current_price: 50000000,
      finish_price: null,
      winner_user: JSON.stringify([]),
      images: JSON.stringify(['house1-1.jpg', 'house1-2.jpg', 'house1-3.jpg']),
      main_image: 'house1-main.jpg',
      country: 'Казахстан',
      city: 'Алматы',
      street: 'ул. Озерная',
      address: 'д. 15',
      year: 2020,
      auction_start_date: new Date('2026-02-01 10:00:00'),
      area: 250,
      count_room: 5,
      views_count: 124,
      user_count: 15,
      user_id: 1
    },
    {
      name: 'Современная квартира в центре города',
      prev_text: 'Панорамный вид на город',
      text: 'Роскошная трехкомнатная квартира с панорамными окнами в новом жилом комплексе. Рядом вся инфраструктура.',
      start_price: 35000000,
      current_price: 37500000,
      finish_price: null,
      winner_user: JSON.stringify([]),
      images: JSON.stringify(['flat1-1.jpg', 'flat1-2.jpg']),
      main_image: 'flat1-main.jpg',
      country: 'Казахстан',
      city: 'Алматы',
      street: 'пр. Абая',
      address: 'д. 142, кв. 85',
      year: 2022,
      auction_start_date: new Date('2026-02-02 11:00:00'),
      area: 120,
      count_room: 3,
      views_count: 89,
      user_count: 8,
      user_id: 2
    },
    {
      name: 'Загородный коттедж',
      prev_text: 'Тихое место для семьи',
      text: 'Уютный коттедж за городом с большим участком. Отличное место для тех, кто ценит спокойствие и природу.',
      start_price: 28000000,
      current_price: 30000000,
      finish_price: null,
      winner_user: JSON.stringify([]),
      images: JSON.stringify(['cottage1-1.jpg', 'cottage1-2.jpg', 'cottage1-3.jpg', 'cottage1-4.jpg']),
      main_image: 'cottage1-main.jpg',
      country: 'Казахстан',
      city: 'Алматинская область',
      street: 'ул. Солнечная',
      address: 'уч. 24',
      year: 2019,
      auction_start_date: new Date('2026-02-03 12:00:00'),
      area: 180,
      count_room: 4,
      views_count: 56,
      user_count: 12,
      user_id: 2
    },
    {
      name: 'Элитная квартира с террасой',
      prev_text: 'Премиум класс',
      text: 'Просторная квартира в элитном районе с собственной террасой. Дизайнерский ремонт, встроенная техника.',
      start_price: 45000000,
      current_price: 45000000,
      finish_price: null,
      winner_user: JSON.stringify([]),
      images: JSON.stringify(['elite1-1.jpg', 'elite1-2.jpg']),
      main_image: 'elite1-main.jpg',
      country: 'Казахстан',
      city: 'Алматы',
      street: 'ул. Достык',
      address: 'д. 78, кв. 152',
      year: 2023,
      auction_start_date: new Date('2026-02-04 13:00:00'),
      area: 140,
      count_room: 3,
      views_count: 102,
      user_count: 6,
      user_id: 3
    },
    {
      name: 'Таунхаус в новом ЖК',
      prev_text: 'Современное решение для семьи',
      text: 'Двухэтажный таунхаус в охраняемом жилом комплексе. Собственная парковка, детская площадка.',
      start_price: 32000000,
      current_price: 33500000,
      finish_price: null,
      winner_user: JSON.stringify([]),
      images: JSON.stringify(['townhouse1-1.jpg', 'townhouse1-2.jpg', 'townhouse1-3.jpg']),
      main_image: 'townhouse1-main.jpg',
      country: 'Казахстан',
      city: 'Нур-Султан',
      street: 'ул. Кабанбай батыра',
      address: 'ЖК Панорама, секция B-12',
      year: 2021,
      auction_start_date: new Date('2026-02-05 14:00:00'),
      area: 160,
      count_room: 4,
      views_count: 73,
      user_count: 9,
      user_id: 1
    },
    {
      name: 'Просторная студия',
      prev_text: 'Идеально для молодой пары',
      text: 'Современная студия с качественным ремонтом. Удобная планировка, рядом метро и торговые центры.',
      start_price: 18000000,
      current_price: 19000000,
      finish_price: null,
      winner_user: JSON.stringify([]),
      images: JSON.stringify(['studio1-1.jpg', 'studio1-2.jpg']),
      main_image: 'studio1-main.jpg',
      country: 'Казахстан',
      city: 'Алматы',
      street: 'пр. Райымбека',
      address: 'д. 220, кв. 34',
      year: 2023,
      auction_start_date: new Date('2026-02-06 15:00:00'),
      area: 45,
      count_room: 1,
      views_count: 145,
      user_count: 18,
      user_id: 3
    },
    {
      name: 'Вилла с бассейном',
      prev_text: 'Роскошь и комфорт',
      text: 'Шикарная вилла с открытым бассейном, большим садом и зоной барбекю. Для ценителей комфорта.',
      start_price: 75000000,
      current_price: 75000000,
      finish_price: null,
      winner_user: JSON.stringify([]),
      images: JSON.stringify(['villa1-1.jpg', 'villa1-2.jpg', 'villa1-3.jpg', 'villa1-4.jpg', 'villa1-5.jpg']),
      main_image: 'villa1-main.jpg',
      country: 'Казахстан',
      city: 'Алматы',
      street: 'ул. Горная',
      address: 'уч. 8',
      year: 2021,
      auction_start_date: new Date('2026-02-07 16:00:00'),
      area: 320,
      count_room: 6,
      views_count: 67,
      user_count: 4,
      user_id: 1
    },
    {
      name: 'Квартира с ремонтом',
      prev_text: 'Готова к проживанию',
      text: 'Двухкомнатная квартира с современным ремонтом. Вся мебель и техника остаются новым владельцам.',
      start_price: 25000000,
      current_price: 26500000,
      finish_price: null,
      winner_user: JSON.stringify([]),
      images: JSON.stringify(['flat2-1.jpg', 'flat2-2.jpg', 'flat2-3.jpg']),
      main_image: 'flat2-main.jpg',
      country: 'Казахстан',
      city: 'Шымкент',
      street: 'ул. Байтурсынова',
      address: 'д. 56, кв. 42',
      year: 2020,
      auction_start_date: new Date('2026-02-08 10:30:00'),
      area: 65,
      count_room: 2,
      views_count: 91,
      user_count: 11,
      user_id: 2
    },
    {
      name: 'Пентхаус с видом на горы',
      prev_text: 'Эксклюзивное предложение',
      text: 'Роскошный пентхаус на последнем этаже с панорамным видом на горы. Собственная крыша-терраса.',
      start_price: 95000000,
      current_price: 95000000,
      finish_price: null,
      winner_user: JSON.stringify([]),
      images: JSON.stringify(['penthouse1-1.jpg', 'penthouse1-2.jpg', 'penthouse1-3.jpg']),
      main_image: 'penthouse1-main.jpg',
      country: 'Казахстан',
      city: 'Алматы',
      street: 'пр. Аль-Фараби',
      address: 'д. 95, пентхаус 1',
      year: 2024,
      auction_start_date: new Date('2026-02-09 11:00:00'),
      area: 200,
      count_room: 4,
      views_count: 234,
      user_count: 22,
      user_id: 3
    },
    {
      name: 'Дом в экологически чистом районе',
      prev_text: 'Близость к природе',
      text: 'Отдельно стоящий дом в тихом районе, окруженный лесом. Свежий воздух и тишина гарантированы.',
      start_price: 38000000,
      current_price: 40000000,
      finish_price: null,
      winner_user: JSON.stringify([]),
      images: JSON.stringify(['house2-1.jpg', 'house2-2.jpg', 'house2-3.jpg', 'house2-4.jpg']),
      main_image: 'house2-main.jpg',
      country: 'Казахстан',
      city: 'Караганда',
      street: 'ул. Лесная',
      address: 'д. 32',
      year: 2018,
      auction_start_date: new Date('2026-02-10 12:00:00'),
      area: 190,
      count_room: 5,
      views_count: 78,
      user_count: 7,
      user_id: 1
    }
  ]);
};
